export type IntentKind="investigate"|"compare"|"plan"|"create"|"retrieve"|"explain"|"monitor"|"unknown";
export type ResolvedIntent={kind:IntentKind;label:string;normalizedRequest:string;requiredCapabilities:string[];needsBusinessData:boolean;needsExternalResearch:boolean;ambiguity:"none"|"material"};
const rules:Array<{kind:IntentKind;label:string;patterns:RegExp[];capabilities:string[]}>= [
{kind:"investigate",label:"Investigate a business situation",patterns:[/\bwhy\b/i,/\bdeclin/i,/\bdrop/i,/\bfall/i,/\bchanged/i,/\bcaus/i,/\binvestigat/i],capabilities:["business-analysis","evidence-review"]},
{kind:"compare",label:"Compare options or entities",patterns:[/\bcompar/i,/\bversus\b/i,/\bvs\.?\b/i,/\bwhich\b/i,/\bbetween\b/i],capabilities:["comparison","evidence-review"]},
{kind:"plan",label:"Build a plan",patterns:[/\bplan\b/i,/\broadmap\b/i,/\bstrategy\b/i,/\b90[- ]day\b/i],capabilities:["planning","business-context"]},
{kind:"create",label:"Create a business output",patterns:[/\bcreate\b/i,/\bwrite\b/i,/\bdraft\b/i,/\bprepare\b/i,/\bmake\b/i],capabilities:["content-generation","business-context"]},
{kind:"retrieve",label:"Retrieve business information",patterns:[/\bshow\b/i,/\bfind\b/i,/\blist\b/i,/\bhow much\b/i,/\bwhat is\b/i],capabilities:["business-data-retrieval"]},
{kind:"explain",label:"Explain something",patterns:[/\bexplain\b/i,/\bteach\b/i,/\bhelp me understand\b/i],capabilities:["explanation"]},
{kind:"monitor",label:"Monitor a business condition",patterns:[/\bmonitor\b/i,/\btrack\b/i,/\bwatch\b/i,/\balert\b/i],capabilities:["monitoring","business-context"]}];
export function resolveIntent(input:string):ResolvedIntent{const request=input.trim().replace(/\s+/g," ");if(!request)return{kind:"unknown",label:"No request yet",normalizedRequest:"",requiredCapabilities:[],needsBusinessData:false,needsExternalResearch:false,ambiguity:"none"};const matched=rules.find(r=>r.patterns.some(p=>p.test(request)));const external=/\bmarket\b|\bcompetitor\b|\bindustry\b|\bregulat/i.test(request);const business=/\bsales\b|\brevenue\b|\bcustomer\b|\bprofit\b|\bcash\b|\binventory\b|\bsupplier\b|\bexpense\b|\bbusiness\b/i.test(request);if(!matched)return{kind:"unknown",label:"Understand the request before choosing a capability",normalizedRequest:request,requiredCapabilities:["intent-resolution"],needsBusinessData:business,needsExternalResearch:external,ambiguity:"none"};return{kind:matched.kind,label:matched.label,normalizedRequest:request,requiredCapabilities:matched.capabilities,needsBusinessData:business,needsExternalResearch:external,ambiguity:"none"};}