import type { EvidenceItem, ReasoningType } from "./types.js";
import type { BusinessStage } from "../bie/intent.js";

export type IntentStage = "pre-business" | "existing-business" | "general";

export type IntentState = {
  stage: IntentStage;
  desiredOutcome: string;
  uncertainty: "low" | "medium" | "high";
  scope: "personal" | "business" | "external" | "general";
};

export type PossibilityStatus = "candidate" | "supported" | "challenged" | "rejected" | "unresolved";

export type Possibility = {
  id: string;
  type: "hypothesis" | "opportunity" | "scenario" | "option";
  statement: string;
  status: PossibilityStatus;
  evidenceIds: string[];
  assumptions: string[];
  unknowns: string[];
};

export type ActualState = {
  id: string;
  kind: "observed" | "inferred" | "assumed" | "hypothesized" | "unknown";
  statement: string;
  evidenceIds: string[];
  confidence: "high" | "medium" | "low";
};

export type PossibilityMemory = {
  id: string;
  label: string;
  statement: string;
  type: Possibility["type"];
  status: PossibilityStatus;
  ordinal: number;
  evidenceIds: string[];
  assumptions: string[];
  unknowns: string[];
  source: "user" | "busiq" | "evidence";
};

export type SemanticModel = {
  intent: IntentState;
  possibilities: Possibility[];
  actual: ActualState[];
  possibilityMemory: PossibilityMemory[];
};

function inferStageFromIntent(intentKind: string): IntentStage {
  if (intentKind === "investigate" || intentKind === "monitor") return "existing-business";
  return "general";
}

function desiredOutcomeFromIntent(intentKind: string): string {
  switch (intentKind) {
    case "investigate": return "Understand what is happening and determine which explanations are supported by evidence.";
    case "compare": return "Compare relevant alternatives using explicit criteria and available evidence.";
    case "plan": return "Produce a structured plan grounded in available context and explicit assumptions.";
    case "create": return "Produce the requested artifact without inventing unsupported facts.";
    case "retrieve": return "Retrieve the requested information from available evidence.";
    case "explain": return "Explain the requested subject clearly and accurately.";
    default: return "Fulfil the user's requested outcome.";
  }
}

export function buildSemanticModel(
  request: string,
  evidence: EvidenceItem[],
  intentKind: string,
  reasoningTypes: ReasoningType[] = [],
  priorPossibilities: PossibilityMemory[] = [],
  semanticContext?: { businessStage: BusinessStage; desiredOutcome: string },
): SemanticModel {
  const stage = semanticContext?.businessStage === "pre-business" || semanticContext?.businessStage === "existing-business"
    ? semanticContext.businessStage
    : inferStageFromIntent(intentKind);
  const hasVerified = evidence.some(item => item.verification === "verified" || item.kind === "verified" || item.kind === "retrieved");
  const hasUserEvidence = evidence.some(item => item.kind === "user");
  const uncertainty: IntentState["uncertainty"] =
    stage === "pre-business" ? "high" : hasVerified ? "medium" : hasUserEvidence ? "medium" : "high";

  const possibilities: Possibility[] = [];
  if (stage === "pre-business") {
    possibilities.push({
      id: "opportunity-space",
      type: "opportunity",
      statement: "Potential business opportunities compatible with the user's stated constraints.",
      status: "candidate",
      evidenceIds: evidence.filter(e => e.kind === "retrieved" || e.kind === "verified").map(e => e.id),
      assumptions: ["The user's stated constraints are accurate and sufficiently complete."],
      unknowns: ["Customer demand", "willingness to pay", "competitive intensity", "delivery economics"],
    });
  }
  if (intentKind === "investigate") {
    possibilities.push({
      id: "investigation-hypotheses",
      type: "hypothesis",
      statement: "Candidate explanations generated by the investigation engine require evidence testing before becoming conclusions.",
      status: "unresolved",
      evidenceIds: evidence.map(e => e.id),
      assumptions: [],
      unknowns: ["Which candidate explanation is causally supported."],
    });
  }

  const possibilityMemory: PossibilityMemory[] = [
    ...priorPossibilities,
    ...possibilities.map((possibility, index) => ({
      id: possibility.id,
      label: `Option ${index + 1}`,
      statement: possibility.statement,
      type: possibility.type,
      status: possibility.status,
      ordinal: index + 1,
      evidenceIds: possibility.evidenceIds,
      assumptions: possibility.assumptions,
      unknowns: possibility.unknowns,
      source: "busiq" as const,
    })),
  ];

  const actual: ActualState[] = evidence.map(item => ({
    id: item.id,
    kind: item.kind === "verified" || item.kind === "retrieved" ? "observed" : item.kind === "inferred" ? "inferred" : "assumed",
    statement: item.detail,
    evidenceIds: [item.id],
    confidence: item.verification === "verified" ? "high" : item.kind === "retrieved" ? "medium" : "low",
  }));

  if (reasoningTypes.includes("INFERENCE")) {
    actual.push({
      id: "reasoning-inferences",
      kind: "inferred",
      statement: "Some conclusions are derived from available evidence rather than directly observed.",
      evidenceIds: evidence.map(e => e.id),
      confidence: hasVerified ? "medium" : "low",
    });
  }

  if (!actual.length) {
    actual.push({
      id: "insufficient-actual-evidence",
      kind: "unknown",
      statement: "No business or external evidence has been established yet.",
      evidenceIds: [],
      confidence: "low",
    });
  }

  return {
    intent: {
      stage,
      desiredOutcome: semanticContext?.desiredOutcome ?? desiredOutcomeFromIntent(intentKind),
      uncertainty,
      scope: stage === "existing-business" ? "business" : stage === "pre-business" ? "personal" : "general",
    },
    possibilities,
    actual,
    possibilityMemory,
  };
}
