import type { EvidenceItem, ReasoningType } from "./types.js";

export type IntentStage = "pre-business" | "existing-business" | "general";

export type IntentState = {
  stage: IntentStage;
  desiredOutcome: string;
  uncertainty: "low" | "medium" | "high";
  scope: "personal" | "business" | "external" | "general";
};

export type PossibilityStatus = "candidate" | "supported" | "challenged" | "rejected" | "unresolved";

export type Possibility = {
  id: string;
  type: "hypothesis" | "opportunity" | "scenario" | "option";
  statement: string;
  status: PossibilityStatus;
  evidenceIds: string[];
  assumptions: string[];
  unknowns: string[];
};

export type ActualState = {
  id: string;
  kind: "observed" | "inferred" | "assumed" | "hypothesized" | "unknown";
  statement: string;
  evidenceIds: string[];
  confidence: "high" | "medium" | "low";
};

export type PossibilityMemory = {
  id: string;
  label: string;
  statement: string;
  type: Possibility["type"];
  status: PossibilityStatus;
  ordinal: number;
  evidenceIds: string[];
  assumptions: string[];
  unknowns: string[];
  source: "user" | "busiq" | "evidence";
};

export type SemanticModel = {
  intent: IntentState;
  possibilities: Possibility[];
  actual: ActualState[];
  possibilityMemory: PossibilityMemory[];
};

function inferStage(request: string): IntentStage {
  const preBusiness = /\b(start|build|launch|create)\b.*\b(business|company|venture)\b|\b(no|don't have|do not have)\b.*\b(business|idea)\b|\bwhat business should i\b/i;
  if (preBusiness.test(request)) return "pre-business";
  if (/\b(my|our|current|existing)\b.*\b(business|company|sales|customers|inventory|profit|revenue)\b/i.test(request)) return "existing-business";
  return "general";
}

function desiredOutcome(request: string, stage: IntentStage): string {
  if (stage === "pre-business") return "Identify and validate a business opportunity that fits the user's stated constraints.";
  if (/\bwhy\b|\binvestigat/i.test(request)) return "Understand what changed and determine which explanations are supported by evidence.";
  if (/\bcompare|versus|vs\\.?\b/i.test(request)) return "Compare alternatives using relevant evidence and assumptions.";
  if (/\bplan|roadmap|strategy/i.test(request)) return "Produce a structured plan grounded in the available context and explicit assumptions.";
  return "Fulfil the user's requested business or informational outcome.";
}

export function buildSemanticModel(
  request: string,
  evidence: EvidenceItem[],
  intentKind: string,
  reasoningTypes: ReasoningType[] = [],
  priorPossibilities: PossibilityMemory[] = [],
): SemanticModel {
  const stage = inferStage(request);
  const hasVerified = evidence.some(item => item.verification === "verified" || item.kind === "verified" || item.kind === "retrieved");
  const hasUserEvidence = evidence.some(item => item.kind === "user");
  const uncertainty: IntentState["uncertainty"] =
    stage === "pre-business" ? "high" : hasVerified ? "medium" : hasUserEvidence ? "medium" : "high";

  const possibilities: Possibility[] = [];
  if (stage === "pre-business") {
    possibilities.push({
      id: "opportunity-space",
      type: "opportunity",
      statement: "Potential business opportunities compatible with the user's stated constraints.",
      status: "candidate",
      evidenceIds: evidence.filter(e => e.kind === "retrieved" || e.kind === "verified").map(e => e.id),
      assumptions: ["The user's stated constraints are accurate and sufficiently complete."],
      unknowns: ["Customer demand", "willingness to pay", "competitive intensity", "delivery economics"],
    });
  }
  if (intentKind === "investigate") {
    possibilities.push({
      id: "investigation-hypotheses",
      type: "hypothesis",
      statement: "Candidate explanations generated by the investigation engine require evidence testing before becoming conclusions.",
      status: "unresolved",
      evidenceIds: evidence.map(e => e.id),
      assumptions: [],
      unknowns: ["Which candidate explanation is causally supported."],
    });
  }

  const possibilityMemory: PossibilityMemory[] = [
    ...priorPossibilities,
    ...possibilities.map((possibility, index) => ({
      id: possibility.id,
      label: `Option ${index + 1}`,
      statement: possibility.statement,
      type: possibility.type,
      status: possibility.status,
      ordinal: index + 1,
      evidenceIds: possibility.evidenceIds,
      assumptions: possibility.assumptions,
      unknowns: possibility.unknowns,
      source: "busiq" as const,
    })),
  ];

  const actual: ActualState[] = evidence.map(item => ({
    id: item.id,
    kind: item.kind === "verified" || item.kind === "retrieved" ? "observed" : item.kind === "inferred" ? "inferred" : "assumed",
    statement: item.detail,
    evidenceIds: [item.id],
    confidence: item.verification === "verified" ? "high" : item.kind === "retrieved" ? "medium" : "low",
  }));

  if (reasoningTypes.includes("INFERENCE")) {
    actual.push({
      id: "reasoning-inferences",
      kind: "inferred",
      statement: "Some conclusions are derived from available evidence rather than directly observed.",
      evidenceIds: evidence.map(e => e.id),
      confidence: hasVerified ? "medium" : "low",
    });
  }

  if (!actual.length) {
    actual.push({
      id: "insufficient-actual-evidence",
      kind: "unknown",
      statement: "No business or external evidence has been established yet.",
      evidenceIds: [],
      confidence: "low",
    });
  }

  return {
    intent: {
      stage,
      desiredOutcome: desiredOutcome(request, stage),
      uncertainty,
      scope: stage === "existing-business" ? "business" : stage === "pre-business" ? "personal" : "general",
    },
    possibilities,
    actual,
    possibilityMemory,
  };
}
